### ISSUE TITLE
Surprising (non)collision between player character and ceiling

### ISSUE THREAD

**Issue by Viir** [passiomatic/sunny-land#1]
The ability to jump to maximum height here surprised me. It looks like we jump through a ceiling:
![2021-04-20-sunny-land-sorpresa](https://user-images.githubusercontent.com/19209696/115386193-9c22f580-a1c8-11eb-8613-590130154aae.gif)

**Comment by passiomatic** [comment]
Just noticed that the level has the wall drawn like this:

![Schermata 2021-04-20 alle 14 41 42](https://user-images.githubusercontent.com/56371/115397699-abb13700-a1e6-11eb-82e2-823415ffecfd.png)

I'll edit the level and refresh online version.
